package encapsulation;

public class BankDriver {

	public static void main(String[] args) 
	{
		//HERE I CRETED A OBJECTS TO LOAD THE DATA WITH THE HELP OF REFERENCE VARIABLE WE CAN ACCESS THE ELEMENTS
		Bank b=new Bank("DIPAK BHADANE",9822946959L,1234,12000);
		// (b.data()) IS USED TO CALL ALL DETAILS
		b.data();
		//HERE I USED VALIDATION AND VERIFICATION
		//HERE I CHANGING THE NAME OF ACCOUNT HOLDER BY VERIFYING OR ENTERING UPI PIN
		b.setAcc_hol_name("DEEPAK BHADANE",1234);
		b.data();
		//HERE I CHANGING THE ACCOUNT NUMBER OF ACCOUNT HOLDER BY VERIFYING OR ENTERING UPI PIN
		b.setAcc_Number(7020225669l, 1234);
		b.data();
		//HERE I CHANGING THE BALANCE OF ACCOUNT HOLDER BY VERIFYING OR ENTERING UPI PIN
		b.setAcc_Balance(40000, 1234);
		b.data();
		//Bank b1=b;
		//b1.data();
	}
}